url: https://github.com/longhorn/charts.git
subdirectory: charts/longhorn
commit: 6236ffb9116905d109c3beee757ce308e1d9aa12
version: 100.1.1
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
    addCRDValidationToMainChart: true
